version: "3"
services:
  frontend:
    image: phnx-newfrontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - phoenix-emart
  api-server:
    image: digvijay777/phoenix-backend:dev
    ports:
      - "8000:8000"
    networks:
      - phoenix-emart
networks:
  phoenix-emart:
    driver: bridge  





