version: "3"
services:
  frontend:
    image: digvijay777/phnx-newfrontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - phoenix-emart
  api-server:
    image: digvijay777/phoenix-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - redis-server
    networks:
      - phoenix-emart
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
networks:
  phoenix-emart:
    driver: bridge





