name: Build and Deploy

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./Backend
        run: npm install

      - name: Create .env file
        working-directory: ./Backend
        run: |
          touch .env
          echo "MONGO_DB_NAME=mongodb+srv://parthirache8:ufPeWVX7HabgpyVh@cluster0.eo9svyz.mongodb.net/Phoenix-E-Mart" >> .env
          echo "MONGO_DB_TEST=mongodb+srv://parthirache8:ufPeWVX7HabgpyVh@cluster0.eo9svyz.mongodb.net/test" >> .env

      - name: Run test
        working-directory: ./Backend
        run: |
          npm test
          if [ $? -ne 0 ]; then
            echo "Tests failed, exiting."
            exit 1
          fi

      - name: Build Docker Image for Server
        working-directory: ./Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME1 }}/phoenix-backend .

      - name: Build Docker Image for Frontend
        working-directory: ./Phoenix-E-Mart
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME1 }}/phnx-newfrontend .        

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME2 }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to DockerHub
        working-directory: ./Backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME1 }}/phoenix-backend

      - name: Push Image to DockerHub
        working-directory: ./Phoenix-E-Mart
        run: |
          docker push ${{ secrets.DOCKER_USERNAME1 }}/phnx-newfrontend
